# Generated by Django 5.1 on 2024-11-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.CharField(max_length=100)),
                ('file_date', models.CharField(max_length=100)),
                ('agmt_type', models.CharField(max_length=100)),
                ('dv_url', models.CharField(max_length=100)),
                ('classdesc', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('schooldesc', models.CharField(max_length=100)),
                ('munidesc', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('bk_vol_pg', models.CharField(max_length=100)),
                ('usedesc', models.CharField(max_length=100)),
                ('calcacreag', models.CharField(max_length=100)),
                ('fairmarkettotal', models.CharField(max_length=100)),
                ('geomjson', models.CharField(max_length=250)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=100)),
                ('geomjson', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wellsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_num', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('geomjson', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wellsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_num', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('geomjson', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
