# Generated by Django 5.1.2 on 2024-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.CharField(max_length=100)),
                ('file_date', models.CharField(max_length=100)),
                ('agmt_type', models.CharField(max_length=100)),
                ('dv_url', models.CharField(max_length=100)),
                ('classdesc', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('schooldesc', models.CharField(max_length=100)),
                ('munidesc', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('bk_vol_pg', models.CharField(max_length=100)),
                ('usedesc', models.CharField(max_length=100)),
                ('calcacreag', models.CharField(max_length=100)),
                ('fairmarkettotal', models.CharField(max_length=100)),
                ('geomjson', models.CharField()),
            ],
            options={
                'db_table': 'parcel_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_num', models.CharField(blank=True, max_length=50, null=True)),
                ('other_id', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('well_name', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('spud_date', models.CharField(blank=True, max_length=50, null=True)),
                ('plug_date', models.CharField(blank=True, max_length=50, null=True)),
                ('well_type', models.CharField(blank=True, max_length=50, null=True)),
                ('well_status', models.CharField(blank=True, max_length=50, null=True)),
                ('well_configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_category', models.CharField(blank=True, max_length=50, null=True)),
                ('wellwiki', models.CharField(blank=True, max_length=50, null=True)),
                ('src_url', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wells15',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField()),
                ('geomjson', models.CharField()),
            ],
            options={
                'db_table': 'allegheny_polygons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wells15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_num', models.CharField(blank=True, max_length=50, null=True)),
                ('other_id', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('well_name', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('spud_date', models.CharField(blank=True, max_length=50, null=True)),
                ('plug_date', models.CharField(blank=True, max_length=50, null=True)),
                ('well_type', models.CharField(blank=True, max_length=50, null=True)),
                ('well_status', models.CharField(blank=True, max_length=50, null=True)),
                ('well_configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_category', models.CharField(blank=True, max_length=50, null=True)),
                ('wellwiki', models.CharField(blank=True, max_length=50, null=True)),
                ('src_url', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellsdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wells_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_num', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('geomjson', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wells_allegh_c',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wells_U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_num', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('geomjson', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wells_allegh_u',
                'managed': False,
            },
        ),
    ]
